name: Creatazon
description: Creates amazon accounts
# version: 1.0.0
# homepage: https://www.example.com
# author: RubbaBoy <adamyarris@yahoo.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  path: ^1.6.0
  webdriver: ^2.1.1
  args: ^1.5.2
  process_run: ^0.10.2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
